// 博館分隊救護義消協勤系統 - 初始示範資料庫
// 根據真實排班表與官方出勤紀錄表製作

export const INITIAL_MEMBERS = [
  { id: 'm0', name: '分隊警消承辦人', idNo: 'B120000001', role: '分隊警消承辦人', level: '分隊承辦人 (最高全域管理權限)', avatar: '👮‍♂️', phone: '04-23210119', joined: '博館分隊', totalHours: 999.0, totalDispatches: 999, roscCount: 99, ecgCount: 99, ivCount: 99, isRestricted: false, restrictionUntil: null, makeupTrainingStatus: 'eligible' },
  { id: 'm1', name: '謝易庭', idNo: 'L123668055', role: '救護義消隊員', level: 'EMT-2', avatar: '👨‍🚒', phone: '0912-345678', joined: '111年3月', totalHours: 326.5, totalDispatches: 142, roscCount: 3, ecgCount: 22, ivCount: 31, isRestricted: false, restrictionUntil: null, makeupTrainingStatus: 'eligible' },
  { id: 'm2', name: '林振傑', idNo: 'L124436637', role: '救護義消小隊長', level: 'EMT-P (TP)', avatar: '👨‍⚕️', phone: '0922-888999', joined: '108年6月', totalHours: 580.0, totalDispatches: 268, roscCount: 7, ecgCount: 45, ivCount: 68, isRestricted: false, restrictionUntil: null, makeupTrainingStatus: 'eligible' },
  { id: 'm3', name: '張宥安', idNo: 'L126104316', role: '救護義消幹部', level: 'EMT-2', avatar: '👨‍🚒', phone: '0933-111222', joined: '112年1月', totalHours: 245.0, totalDispatches: 98, roscCount: 2, ecgCount: 16, ivCount: 19, isRestricted: false, restrictionUntil: null, makeupTrainingStatus: 'eligible' },
  { id: 'm4', name: '楊雅晶', idNo: 'B222429727', role: '救護義消隊員', level: 'EMT-2', avatar: '👩‍🚒', phone: '0955-666777', joined: '112年5月', totalHours: 198.5, totalDispatches: 86, roscCount: 1, ecgCount: 12, ivCount: 24, isRestricted: false, restrictionUntil: null, makeupTrainingStatus: 'eligible' },
  { id: 'm5', name: '張鎔堤', idNo: 'B123441467', role: '救護義消隊員', level: 'EMT-1', avatar: '👨‍🚒', phone: '0966-222333', joined: '113年2月', totalHours: 142.0, totalDispatches: 61, roscCount: 1, ecgCount: 8, ivCount: 11, isRestricted: false, restrictionUntil: null, makeupTrainingStatus: 'eligible' },
  { id: 'm6', name: '周思瑩', idNo: 'B221850406', role: '救護義消隊員', level: 'EMT-2', avatar: '👩‍⚕️', phone: '0977-444555', joined: '111年9月', totalHours: 289.0, totalDispatches: 125, roscCount: 4, ecgCount: 19, ivCount: 28, isRestricted: false, restrictionUntil: null, makeupTrainingStatus: 'eligible' },
  { id: 'm7', name: '彭凱琳', idNo: 'N224165440', role: '救護義消幹部', level: 'EMT-2', avatar: '👩‍🚒', phone: '0988-333444', joined: '110年8月', totalHours: 412.0, totalDispatches: 180, roscCount: 5, ecgCount: 26, ivCount: 42, isRestricted: false, restrictionUntil: null, makeupTrainingStatus: 'eligible' },
  { id: 'm8', name: '韓寧', idNo: 'A227685019', role: '救護義消隊員', level: 'EMT-1', avatar: '👩‍🚒', phone: '0911-777888', joined: '113年7月', totalHours: 64.0, totalDispatches: 24, roscCount: 0, ecgCount: 4, ivCount: 3, isRestricted: false, restrictionUntil: null, makeupTrainingStatus: 'eligible' },
  { id: 'm9', name: '陳尚璆', idNo: 'T124111810', role: '救護義消隊員', level: 'EMT-2', avatar: '👨‍🚒', phone: '0928-999000', joined: '112年8月', totalHours: 175.5, totalDispatches: 72, roscCount: 2, ecgCount: 14, ivCount: 15, isRestricted: false, restrictionUntil: null, makeupTrainingStatus: 'eligible' },
  { id: 'm10', name: '洪銘聰', idNo: 'B122652653', role: '救護義消隊員', level: 'EMT-1', avatar: '👨‍🚒', phone: '0937-123789', joined: '113年1月', totalHours: 118.0, totalDispatches: 47, roscCount: 1, ecgCount: 6, ivCount: 8, isRestricted: false, restrictionUntil: null, makeupTrainingStatus: 'eligible' },
  { id: 'm11', name: '黃威傑', idNo: 'B121710361', role: '救護義消隊員', level: 'EMT-2', avatar: '👨‍🚒', phone: '0938-555666', joined: '110年10月', totalHours: 210.0, totalDispatches: 90, roscCount: 2, ecgCount: 11, ivCount: 14, isRestricted: false, restrictionUntil: null, makeupTrainingStatus: 'eligible' },
  { id: 'm12', name: '陳善君', idNo: 'A229489257', role: '救護義消隊員', level: 'EMT-2', avatar: '👩‍🚒', phone: '0939-777111', joined: '111年11月', totalHours: 195.0, totalDispatches: 82, roscCount: 1, ecgCount: 9, ivCount: 12, isRestricted: false, restrictionUntil: null, makeupTrainingStatus: 'eligible' }
];

export const INITIAL_ATTENDANCE = [
  { id: 'att-1', memberId: 'm1', memberName: '謝易庭', date: '115-10-01', signIn: '18:00', signOut: '23:00', hours: 5.0, dispatches: 2, patients: 2, note: '自排班救護協勤 (隊上待命)' },
  { id: 'att-2', memberId: 'm2', memberName: '林振傑', date: '115-10-02', signIn: '07:00', signOut: '18:00', hours: 11.0, dispatches: 4, patients: 3, note: '全日救護協勤 (TP專責支援)' },
  { id: 'att-3', memberId: 'm6', memberName: '周思瑩', date: '115-10-03', signIn: '08:00', signOut: '15:00', hours: 7.0, dispatches: 3, patients: 3, note: '假日早班協勤' },
  { id: 'att-4', memberId: 'm4', memberName: '楊雅晶', date: '115-10-06', signIn: '18:00', signOut: '23:00', hours: 5.0, dispatches: 1, patients: 1, note: '夜間協勤' },
  { id: 'att-5', memberId: 'm5', memberName: '張鎔堤', date: '115-10-06', signIn: '11:00', signOut: '23:00', hours: 12.0, dispatches: 5, patients: 4, note: '假日跨班協勤' },
  { id: 'att-6', memberId: 'm3', memberName: '張宥安', date: '115-10-04', signIn: '14:00', signOut: '18:00', hours: 4.0, dispatches: 1, patients: 1, note: '補定訓值班' },
  { id: 'att-7', memberId: 'm7', memberName: '彭凱琳', date: '115-10-08', signIn: '13:00', signOut: '20:00', hours: 7.0, dispatches: 3, patients: 2, note: '幹部值班協勤' },
  { id: 'att-8', memberId: 'm1', memberName: '謝易庭', date: '115-10-05', signIn: '18:00', signOut: '23:00', hours: 5.0, dispatches: 2, patients: 2, note: '夜間救護協勤 (隊上待命)' },
  { id: 'att-9', memberId: 'm10', memberName: '洪銘聰', date: '115-10-08', signIn: '13:00', signOut: '20:00', hours: 7.0, dispatches: 2, patients: 2, note: '白班協勤' },
  { id: 'att-10', memberId: 'm1', memberName: '謝易庭', date: '115-10-07', signIn: '18:00', signOut: '23:00', hours: 5.0, dispatches: 3, patients: 3, note: '自排班救護協勤' }
];

export const INITIAL_DISPATCHES = [
  {
    id: 'disp-101',
    caseNo: '1151007-01',
    date: '115-10-07',
    vehicle: '博館91',
    departureTime: '19:15',
    returnTime: '20:20',
    location: '臺中市西區館前路與健行路口',
    memberIds: ['m1'],
    memberNames: ['謝易庭'],
    resultType: '送醫',
    patientCount: 1,
    isIdle: false,
    treatments: ['量測生命徵象', '傷口處理', '骨折固定', '搬運'],
    chiefComplaint: '機車擦撞，左膝撕裂傷及左手疑似閉鎖性骨折',
    hospital: '中國醫藥大學附設醫院',
    isSpecial: false,
    specialTag: ''
  },
  {
    id: 'disp-102',
    caseNo: '1151007-02',
    date: '115-10-07',
    vehicle: '博館91',
    departureTime: '21:05',
    returnTime: '22:15',
    location: '臺中市西區公益路二段社區大樓',
    memberIds: ['m1', 'm2'],
    memberNames: ['謝易庭', '林振傑'],
    resultType: '送醫 (OHCA / ROSC成功)',
    patientCount: 1,
    isIdle: false,
    treatments: ['CPR', 'AED', '給氧', '靜脈注射', '12導程心電圖', '搬運'],
    chiefComplaint: '72歲男性突發失去意識倒地無呼吸脈搏，現場CPR+電擊2次於途中恢復心跳(ROSC)',
    hospital: '林新醫院',
    isSpecial: true,
    specialTag: '🌟 現場急救成功 (ROSC)'
  },
  {
    id: 'disp-103',
    caseNo: '1151006-01',
    date: '115-10-06',
    vehicle: '博館92',
    departureTime: '13:40',
    returnTime: '14:25',
    location: '臺中市西區美村路一段',
    memberIds: ['m5'],
    memberNames: ['張鎔堤'],
    resultType: '送醫',
    patientCount: 1,
    isIdle: false,
    treatments: ['量測生命徵象', '給氧', '心理支持', '搬運'],
    chiefComplaint: '65歲女性呼吸急促、胸悶不適',
    hospital: '衛生福利部臺中醫院',
    isSpecial: false,
    specialTag: ''
  },
  {
    id: 'disp-104',
    caseNo: '1151006-02',
    date: '115-10-06',
    vehicle: '博館91',
    departureTime: '19:30',
    returnTime: '20:05',
    location: '臺中市西區台灣大道二段商辦大樓',
    memberIds: ['m4'],
    memberNames: ['楊雅晶'],
    resultType: '空跑 (未發現/取消)',
    patientCount: 0,
    isIdle: true,
    treatments: ['無'],
    chiefComplaint: '報案路倒，到達現場後關係人表示已由家屬自行載返',
    hospital: '無',
    isSpecial: false,
    specialTag: ''
  },
  {
    id: 'disp-105',
    caseNo: '1151005-01',
    date: '115-10-05',
    vehicle: '博館91',
    departureTime: '20:10',
    returnTime: '21:15',
    location: '臺中市西區忠明南路公園旁',
    memberIds: ['m1'],
    memberNames: ['謝易庭'],
    resultType: '送醫',
    patientCount: 1,
    isIdle: false,
    treatments: ['量測生命徵象', '12導程心電圖', '給氧', '靜脈注射', '搬運'],
    chiefComplaint: '58歲男性劇烈胸痛伴隨冷汗，線上ECG傳輸疑似STEMI心肌梗塞',
    hospital: '中國醫藥大學附設醫院',
    isSpecial: true,
    specialTag: '📈 STEMI 早期預警傳輸'
  }
];

export const INITIAL_SHIFTS = [
  {
    "id": "s-1",
    "day": 1,
    "date": "115-10-01",
    "dayOfWeek": "四",
    "vehicle": "救護協勤",
    "period": "18:00-23:00",
    "memberName": "謝易庭",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-5",
    "day": 1,
    "date": "115-10-01",
    "dayOfWeek": "四",
    "vehicle": "救護協勤",
    "period": "18:00-23:00",
    "memberName": "楊雅晶",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-2",
    "day": 2,
    "date": "115-10-02",
    "dayOfWeek": "五",
    "vehicle": "救護協勤",
    "period": "07:00-18:00",
    "memberName": "林振傑",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-3",
    "day": 3,
    "date": "115-10-03",
    "dayOfWeek": "六",
    "vehicle": "救護協勤",
    "period": "08:00-15:00",
    "memberName": "周思瑩",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-6",
    "day": 3,
    "date": "115-10-03",
    "dayOfWeek": "六",
    "vehicle": "救護協勤",
    "period": "11:00-23:00",
    "memberName": "張鎔堤",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-4",
    "day": 3,
    "date": "115-10-03",
    "dayOfWeek": "六",
    "vehicle": "救護協勤",
    "period": "18:00-22:00",
    "memberName": "張宥安",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-20",
    "day": 4,
    "date": "115-10-04",
    "dayOfWeek": "日",
    "vehicle": "救護協勤",
    "period": "08:00-14:00",
    "memberName": "張宥安",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-18",
    "day": 4,
    "date": "115-10-04",
    "dayOfWeek": "日",
    "vehicle": "救護協勤",
    "period": "08:00-18:00",
    "memberName": "陳麗惠",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-22",
    "day": 4,
    "date": "115-10-04",
    "dayOfWeek": "日",
    "vehicle": "救護協勤",
    "period": "09:00-12:00",
    "memberName": "陳筠今",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-10",
    "day": 4,
    "date": "115-10-04",
    "dayOfWeek": "日",
    "vehicle": "救護協勤",
    "period": "10:30-16:00",
    "memberName": "韓寧",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-15",
    "day": 4,
    "date": "115-10-04",
    "dayOfWeek": "日",
    "vehicle": "救護協勤",
    "period": "12:00-21:00",
    "memberName": "陳尚璆",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-7",
    "day": 4,
    "date": "115-10-04",
    "dayOfWeek": "日",
    "vehicle": "救護協勤",
    "period": "14:00-18:00",
    "memberName": "張宥安",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-25",
    "day": 4,
    "date": "115-10-04",
    "dayOfWeek": "日",
    "vehicle": "救護協勤",
    "period": "14:00-18:00",
    "memberName": "林芳儀",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-32",
    "day": 4,
    "date": "115-10-04",
    "dayOfWeek": "日",
    "vehicle": "救護協勤",
    "period": "18:00-22:00",
    "memberName": "簡綉蓉",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-8",
    "day": 4,
    "date": "115-10-04",
    "dayOfWeek": "日",
    "vehicle": "救護協勤",
    "period": "20:30-23:00",
    "memberName": "張鎔堤",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-26",
    "day": 5,
    "date": "115-10-05",
    "dayOfWeek": "一",
    "vehicle": "救護協勤",
    "period": "17:30-23:00",
    "memberName": "張鎔堤",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-11",
    "day": 5,
    "date": "115-10-05",
    "dayOfWeek": "一",
    "vehicle": "救護協勤",
    "period": "18:00-23:00",
    "memberName": "謝易庭",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-27",
    "day": 6,
    "date": "115-10-06",
    "dayOfWeek": "二",
    "vehicle": "救護協勤",
    "period": "16:00-20:00",
    "memberName": "簡綉蓉",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-28",
    "day": 7,
    "date": "115-10-07",
    "dayOfWeek": "三",
    "vehicle": "救護協勤",
    "period": "18:00-21:00",
    "memberName": "莊雅茵",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-12",
    "day": 7,
    "date": "115-10-07",
    "dayOfWeek": "三",
    "vehicle": "救護協勤",
    "period": "18:00-23:00",
    "memberName": "謝易庭",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-29",
    "day": 8,
    "date": "115-10-08",
    "dayOfWeek": "四",
    "vehicle": "救護協勤",
    "period": "18:00-23:00",
    "memberName": "楊雅晶",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-23",
    "day": 9,
    "date": "115-10-09",
    "dayOfWeek": "五",
    "vehicle": "救護協勤",
    "period": "09:00-14:00",
    "memberName": "陳筠今",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-30",
    "day": 9,
    "date": "115-10-09",
    "dayOfWeek": "五",
    "vehicle": "救護協勤",
    "period": "09:00-16:00",
    "memberName": "黃柔迦",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-9",
    "day": 9,
    "date": "115-10-09",
    "dayOfWeek": "五",
    "vehicle": "救護協勤",
    "period": "13:00-20:00",
    "memberName": "彭凱琳",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-13",
    "day": 9,
    "date": "115-10-09",
    "dayOfWeek": "五",
    "vehicle": "救護協勤",
    "period": "13:00-20:00",
    "memberName": "洪銘聰",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-16",
    "day": 9,
    "date": "115-10-09",
    "dayOfWeek": "五",
    "vehicle": "救護協勤",
    "period": "15:30-21:00",
    "memberName": "張宥安",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-14",
    "day": 10,
    "date": "115-10-10",
    "dayOfWeek": "六",
    "vehicle": "救護協勤",
    "period": "07:00-23:00",
    "memberName": "陳尚璆",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-17",
    "day": 10,
    "date": "115-10-10",
    "dayOfWeek": "六",
    "vehicle": "救護協勤",
    "period": "08:00-12:00",
    "memberName": "周思瑩",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-19",
    "day": 10,
    "date": "115-10-10",
    "dayOfWeek": "六",
    "vehicle": "救護協勤",
    "period": "08:00-12:00",
    "memberName": "游順翔",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-31",
    "day": 10,
    "date": "115-10-10",
    "dayOfWeek": "六",
    "vehicle": "救護協勤",
    "period": "09:00-13:00",
    "memberName": "黃柔迦",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-21",
    "day": 10,
    "date": "115-10-10",
    "dayOfWeek": "六",
    "vehicle": "救護協勤",
    "period": "15:00-18:30",
    "memberName": "張宥安",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-24",
    "day": 10,
    "date": "115-10-10",
    "dayOfWeek": "六",
    "vehicle": "救護協勤",
    "period": "18:00-21:00",
    "memberName": "李宜臻",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-34",
    "day": 11,
    "date": "115-10-11",
    "dayOfWeek": "日",
    "vehicle": "救護協勤",
    "period": "07:00-21:00",
    "memberName": "陳尚璆",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-37",
    "day": 11,
    "date": "115-10-11",
    "dayOfWeek": "日",
    "vehicle": "救護協勤",
    "period": "18:00-22:00",
    "memberName": "林芳儀",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-35",
    "day": 13,
    "date": "115-10-13",
    "dayOfWeek": "二",
    "vehicle": "救護協勤",
    "period": "18:00-23:00",
    "memberName": "謝易庭",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-38",
    "day": 13,
    "date": "115-10-13",
    "dayOfWeek": "二",
    "vehicle": "救護協勤",
    "period": "19:00-21:00",
    "memberName": "李宜臻",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-39",
    "day": 15,
    "date": "115-10-15",
    "dayOfWeek": "四",
    "vehicle": "救護協勤",
    "period": "18:00-23:00",
    "memberName": "楊雅晶",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-36",
    "day": 16,
    "date": "115-10-16",
    "dayOfWeek": "五",
    "vehicle": "救護協勤",
    "period": "08:00-17:00",
    "memberName": "邱映儒",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-40",
    "day": 16,
    "date": "115-10-16",
    "dayOfWeek": "五",
    "vehicle": "救護協勤",
    "period": "17:00-21:00",
    "memberName": "楊博安",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-33",
    "day": 17,
    "date": "115-10-17",
    "dayOfWeek": "六",
    "vehicle": "救護協勤",
    "period": "11:00-23:00",
    "memberName": "杜建賢",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-41",
    "day": 18,
    "date": "115-10-18",
    "dayOfWeek": "日",
    "vehicle": "救護協勤",
    "period": "07:00-21:00",
    "memberName": "陳尚璆",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-44",
    "day": 18,
    "date": "115-10-18",
    "dayOfWeek": "日",
    "vehicle": "救護協勤",
    "period": "13:00-17:00",
    "memberName": "林瑀嬛",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-45",
    "day": 19,
    "date": "115-10-19",
    "dayOfWeek": "一",
    "vehicle": "救護協勤",
    "period": "18:00-22:00",
    "memberName": "林芳儀",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-42",
    "day": 20,
    "date": "115-10-20",
    "dayOfWeek": "二",
    "vehicle": "救護協勤",
    "period": "08:00-17:00",
    "memberName": "邱映儒",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-46",
    "day": 20,
    "date": "115-10-20",
    "dayOfWeek": "二",
    "vehicle": "救護協勤",
    "period": "18:00-21:00",
    "memberName": "李宜臻",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-43",
    "day": 21,
    "date": "115-10-21",
    "dayOfWeek": "三",
    "vehicle": "救護協勤",
    "period": "14:00-21:00",
    "memberName": "林奕言",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-47",
    "day": 23,
    "date": "115-10-23",
    "dayOfWeek": "五",
    "vehicle": "救護協勤",
    "period": "17:00-21:00",
    "memberName": "楊博安",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-48",
    "day": 24,
    "date": "115-10-24",
    "dayOfWeek": "六",
    "vehicle": "救護協勤",
    "period": "09:00-12:00",
    "memberName": "陳筠今",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-51",
    "day": 26,
    "date": "115-10-26",
    "dayOfWeek": "一",
    "vehicle": "救護協勤",
    "period": "13:00-17:00",
    "memberName": "林瑀嬛",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-52",
    "day": 28,
    "date": "115-10-28",
    "dayOfWeek": "三",
    "vehicle": "救護協勤",
    "period": "18:00-21:00",
    "memberName": "李宜臻",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-53",
    "day": 30,
    "date": "115-10-30",
    "dayOfWeek": "五",
    "vehicle": "救護協勤",
    "period": "17:00-21:00",
    "memberName": "楊博安",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-54",
    "day": 31,
    "date": "115-10-31",
    "dayOfWeek": "六",
    "vehicle": "救護協勤",
    "period": "09:00-13:00",
    "memberName": "黃柔迦",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-49",
    "day": 31,
    "date": "115-10-31",
    "dayOfWeek": "六",
    "vehicle": "救護協勤",
    "period": "09:00-21:00",
    "memberName": "彭凱琳",
    "status": "已排班",
    "shiftType": "自排班"
  },
  {
    "id": "s-50",
    "day": 31,
    "date": "115-10-31",
    "dayOfWeek": "六",
    "vehicle": "救護協勤",
    "period": "09:00-21:00",
    "memberName": "洪銘聰",
    "status": "已排班",
    "shiftType": "自排班"
  }
];

export const BADGE_DEFINITIONS = [
  {
    id: 'b-1',
    name: '救護百役',
    category: '出勤里程碑',
    icon: '🏆',
    description: '累計跟隨博館救護車出勤超過 100 趟次',
    threshold: 100,
    unit: '次出勤',
    field: 'totalDispatches',
    color: '#f59e0b',
    glow: 'rgba(245, 158, 11, 0.4)'
  },
  {
    id: 'b-2',
    name: '逆轉死神 (ROSC)',
    category: '急救奇蹟',
    icon: '⚡',
    description: '參與現場心肺復甦術並成功於現場或途中恢復自發性心跳 (ROSC)',
    threshold: 1,
    unit: '件急救成功',
    field: 'roscCount',
    color: '#ef4444',
    glow: 'rgba(239, 68, 68, 0.4)'
  },
  {
    id: 'b-3',
    name: '神之心眼 (ECG)',
    category: '專業技能',
    icon: '📈',
    description: '精準操作執行 12 導程心電圖並完成雲端即時判讀傳輸累計 20 例',
    threshold: 20,
    unit: '例ECG',
    field: 'ecgCount',
    color: '#06b6d4',
    glow: 'rgba(6, 182, 212, 0.4)'
  },
  {
    id: 'b-4',
    name: '穿針引線 (IV)',
    category: '救護進階處置',
    icon: '💉',
    description: '重症或創傷急救中成功協助或建立靜脈輸液途徑累計 25 例',
    threshold: 25,
    unit: '例靜脈注射',
    field: 'ivCount',
    color: '#8b5cf6',
    glow: 'rgba(139, 92, 246, 0.4)'
  },
  {
    id: 'b-5',
    name: '守護常勝軍',
    category: '奉獻時數',
    icon: '🛡️',
    description: '年度協勤總時數突破 200 小時，分隊守護中流砥柱',
    threshold: 200,
    unit: '小時協勤',
    field: 'totalHours',
    color: '#10b981',
    glow: 'rgba(16, 185, 129, 0.4)'
  },
  {
    id: 'b-6',
    name: '傳奇鳳凰 (500HR)',
    category: '終身奉獻',
    icon: '👑',
    description: '協勤總時數跨越 500 小時榮譽殿堂',
    threshold: 500,
    unit: '小時協勤',
    field: 'totalHours',
    color: '#ec4899',
    glow: 'rgba(236, 72, 153, 0.4)'
  }
];
